### ISSUE TITLE
Omnimaga master index

### ISSUE THREAD

**Issue by Eeems** [TC01/calcpkg#7]
TODO - have dynamically generated file that follows this format for Omnimaga: http://www.ticalc.org/pub/master.index

```
Index of /files/<cat_id>-<cat_name>

<file_id>-<file_name>.<file_ext>        <file_title>
```

**Comment by Eeems** [comment]
http://www.omnimaga.org/files/master.index

Could you please review this @TC01 and let me know if it will work?

**Comment by Eeems** [comment]
@TC01 Finished implementing the master.index file. I've also implemented allowing you to browse the files like it's a flat filesystem. http://www.omnimaga.org/files/

I'm filtering out stuff from the results where instead of giving a download we give a link to another download page

**Comment by TC01** [comment]
@Eeems: that looks good! Thanks for implementing a flat browsing feature as well; that will make everything much easier.

I should be able to reuse all the code to update repo indices from ticalc.org for Omnimaga, now.

**Comment by Eeems** [comment]
@TC01 Sweet! I'll close this ticket then.
