### ISSUE TITLE
Omnimaga info command

### ISSUE THREAD

**Issue by TC01** [TC01/calcpkg#8]
There isn't a good way to do this at present.

There wasn't a good way to do this before, because there was no way to translate the category names to category IDs short of lots of HTML 

Now, the old Omnimaga archive pages no longer seem to exist since the site is in the process of being upgraded, so it's even less possible (there is only the /files view into the archives). So for now I will just have info return an error (it currently raises a NotImplementedException, I'll make it exit nicely). If the metadata ever comes back I'll look into implementing a proper info.

**Comment by Eeems** [comment]
Tell me what kind of API you need

**Comment by TC01** [comment]
@Eeems: well, the info class as currently written contains the following metadata options:

```
        self.description = ""
        self.repository = ""
        self.category = ""
        self.fileSize = ""
        self.fileDate = ""
        self.sourceCode = ""
        self.author = ""
        self.downloads = ""
        self.documentation = ""
```

Documentation / source code included are ticalc.org specific and not something to worry about here. And repository is set by calcpkg (if the file is from Omnimaga, repository = "omnimaga").

Most of the other information- description, category, date published, size, author, are things that used to be available on the old Omnimaga archive pages. 

So all I really need is a way to get that information from a given /files/.../.../filename. On Cemetech and ticalc.org, we use the file's URL to guess at the file info page's URL, open that info page, and then extract the information from the HTML.

**Comment by Eeems** [comment]
How does giving you a json object for each file if you append "?info" to the url?
ie: http://www.omnimaga.org/files/Old-Calculator-RPGs-Headquarter-Archive/Casio-AFX-series-Graph-100-RPGs/aronstyle.zip would become http://www.omnimaga.org/files/Old-Calculator-RPGs-Headquarter-Archive/Casio-AFX-series-Graph-100-RPGs/aronstyle.zip?info
I could also do some changes to master.index to allow you do get a full json listing if you open http://www.omnimaga.org/files/master.index?json or http://www.omnimaga.org/files/master.index?info

**Comment by TC01** [comment]
Sorry for the delay in getting back to you; the ?info JSON would be perfect, I think.

When you say a full JSON listing, do you mean a single JSON object containing everything, or just a list of all the JSON URLs (that is, a text file listing all the files but with ?info appended to the end of the URLs?) I don't think either would necessarily be of use to me though.

**Comment by Eeems** [comment]
@TC01 Alright, I'll start getting to work on that.

By full JSON listing, I mean a single JSON object containing all the information you would get from the file normally, but in JSON format.
eg:

```
{
 path: '/',
 type: 'folder',
 children: [
  {
   path: '/folder'
   type: 'folder',
   children: []
  },
  {
   path: '/file.ext',
   type: 'file'
  }
 ]
}
```

Of course I'd include a lot more information. I basically build this type of object in PHP every time you make a call to the files. It's pretty much a map of the folder structure based on what is in the database. I then perform searches on it to find the file(s) being called and return the relevant information from it that is needed. It's not really practical large scale, but since the database for this is small enough it works.

**Comment by Eeems** [comment]
Implemented the ?info handling. Re-implemented download counting.
eg: http://www.omnimaga.org/files/Old-Calculator-RPGs-Headquarter-Archive/Casio-AFX-series-Graph-100-RPGs/aronstyle.zip?info

TODO - handle master.index?info

**Comment by TC01** [comment]
Awesome, thanks! I should be able to add info now.

Will close this when I finish doing that.

**Comment by TC01** [comment]
This has been done! Info now works; there is a bit of wonky formatting still (<img> tags, which I can't really do anything about), but nothing to problematic.

Going to close now.
